baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'dotkb'
enableGitInfo = true

[frontmatter]
lastmod = ['lastmod', ':git', 'modified', 'date', 'publishDate']

[markup]
[markup.highlight]
noClasses = false


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Index'
pageRef = '/tree/'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags/'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about/'
weight = 40
